org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=36
REACT_NATIVE_NODE_ALLOW_INSECURE_GLOBALS=true
# org.gradle.java.home is omitted to use system JAVA_HOME (/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home)
MYAPP_UPLOAD_STORE_FILE=markone-release.keystore
MYAPP_UPLOAD_KEY_ALIAS=markone-key
MYAPP_UPLOAD_STORE_PASSWORD=SayAxdVTSmYjl3lB
MYAPP_UPLOAD_KEY_PASSWORD=SayAxdVTSmYjl3lB

